# Bash settings
set -o vi
export EDITOR=/usr/bin/vim
bind -m vi-insert "\C-l":clear-screen
bind -x '"\C-o": "ranger"'
alias ls='ls --color -h --group-directories-first'
alias bashrc="vim ${BASH_SOURCE[0]} -c 'normal zt'"
alias vimrc="vim $HOME/.vimrc"
alias xsessionrc="vim $HOME/.xsessionrc"
alias dwmconfig="vim $HOME/workspace/dwm/dwm*/config.h"
alias dmenuconfig="vim $HOME/workspace/dmenu/dmenu*/config.h"
alias stconfig="vim $HOME/workspace/st/st*/config.h"
# nvidia-settings -a [gpu:0]/GpuPowerMizerMode=1
alias ranger='ranger --choosedir=$HOME/.rangerdir; LASTDIR=`cat $HOME/.rangerdir`; cd "$LASTDIR";'
alias gif='mpv --loop=8'
alias sxiv='sxiv -a -f'

# Tmux
if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
	exec tmux
fi

# Powerline-status
if [ -d "\$HOME/.local/bin" ]; then
	PATH="\$HOME/.local/bin:\$PATH"
fi
export POWERLINE_COMMAND=powerline
if [ -f ~/.local/lib/python3*/site-packages/powerline/bindings/bash/powerline.sh ]; then
	source ~/.local/lib/python3*/site-packages/powerline/bindings/bash/powerline.sh
fi

